// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfqkubdzxfjxxwstiobn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmcWt1YmR6eGZqeHh3c3Rpb2JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjc5NDQsImV4cCI6MjA3MTcwMzk0NH0.6jnkUKT6SffMp2_vK9LfZEwKHGbScq5pi4VIcdTtTkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});